//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.common.utils.model.smmsupload;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataUpload" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encryptAlgorithm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="compressionFormat" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="hashAlgorithm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="dataHash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commandVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idcId",
    "dataUpload",
    "encryptAlgorithm",
    "compressionFormat",
    "hashAlgorithm",
    "dataHash",
    "commandVersion"
})
@XmlRootElement(name = "fileLoad")
public class FileLoad {

    @XmlElement(required = true)
    protected String idcId;
    @XmlElement(required = true)
    protected String dataUpload;
    @XmlElement(required = true)
    protected BigInteger encryptAlgorithm;
    @XmlElement(required = true)
    protected BigInteger compressionFormat;
    @XmlElement(required = true)
    protected BigInteger hashAlgorithm;
    @XmlElement(required = true)
    protected String dataHash;
    @XmlElement(required = true)
    protected String commandVersion;

    /**
     * Gets the value of the idcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcId(String value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the dataUpload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUpload() {
        return dataUpload;
    }

    /**
     * Sets the value of the dataUpload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUpload(String value) {
        this.dataUpload = value;
    }

    /**
     * Gets the value of the encryptAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEncryptAlgorithm() {
        return encryptAlgorithm;
    }

    /**
     * Sets the value of the encryptAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEncryptAlgorithm(BigInteger value) {
        this.encryptAlgorithm = value;
    }

    /**
     * Gets the value of the compressionFormat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompressionFormat() {
        return compressionFormat;
    }

    /**
     * Sets the value of the compressionFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompressionFormat(BigInteger value) {
        this.compressionFormat = value;
    }

    /**
     * Gets the value of the hashAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHashAlgorithm() {
        return hashAlgorithm;
    }

    /**
     * Sets the value of the hashAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHashAlgorithm(BigInteger value) {
        this.hashAlgorithm = value;
    }

    /**
     * Gets the value of the dataHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataHash() {
        return dataHash;
    }

    /**
     * Sets the value of the dataHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataHash(String value) {
        this.dataHash = value;
    }

    /**
     * Gets the value of the commandVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandVersion() {
        return commandVersion;
    }

    /**
     * Sets the value of the commandVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandVersion(String value) {
        this.commandVersion = value;
    }

}
