//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.common.utils.model.smmsupload;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="logAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="endFlag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="msgInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="log" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="logId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="srcIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="destIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="srcPort" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="destPort" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="accessTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandId",
    "idcId",
    "result",
    "log",
    "timeStamp"
})
@XmlRootElement(name = "logQueryResult")
public class LogQueryResult {

    protected long commandId;
    @XmlElement(required = true)
    protected String idcId;
    @XmlElement(required = true)
    protected Result result;
    protected List<Log> log;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the commandId property.
     *
     */
    public long getCommandId() {
        return commandId;
    }

    /**
     * Sets the value of the commandId property.
     *
     */
    public void setCommandId(long value) {
        this.commandId = value;
    }

    /**
     * Gets the value of the idcId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdcId(String value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return
     *     possible object is
     *     {@link Result }
     *
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value
     *     allowed object is
     *     {@link Result }
     *
     */
    public void setResult(Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the log property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log }
     *
     *
     */
    public List<Log> getLog() {
        if (log == null) {
            log = new ArrayList<Log>();
        }
        return this.log;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="logId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="srcIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="destIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="srcPort" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="destPort" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="accessTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "logId",
        "houseId",
        "srcIp",
        "destIp",
        "srcPort",
        "destPort",
        "url",
        "accessTime"
    })
    public static class Log {

        protected long logId;
        protected long houseId;
        @XmlElement(required = true)
        protected String srcIp;
        @XmlElement(required = true)
        protected String destIp;
        protected long srcPort;
        protected long destPort;
        protected String url;
        @XmlElement(required = true)
        protected String accessTime;

        /**
         * Gets the value of the logId property.
         * 
         */
        public long getLogId() {
            return logId;
        }

        /**
         * Sets the value of the logId property.
         * 
         */
        public void setLogId(long value) {
            this.logId = value;
        }

        /**
         * Gets the value of the houseId property.
         * 
         */
        public long getHouseId() {
            return houseId;
        }

        /**
         * Sets the value of the houseId property.
         * 
         */
        public void setHouseId(long value) {
            this.houseId = value;
        }

        /**
         * Gets the value of the srcIp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcIp() {
            return srcIp;
        }

        /**
         * Sets the value of the srcIp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcIp(String value) {
            this.srcIp = value;
        }

        /**
         * Gets the value of the destIp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestIp() {
            return destIp;
        }

        /**
         * Sets the value of the destIp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestIp(String value) {
            this.destIp = value;
        }

        /**
         * Gets the value of the srcPort property.
         * 
         */
        public long getSrcPort() {
            return srcPort;
        }

        /**
         * Sets the value of the srcPort property.
         * 
         */
        public void setSrcPort(long value) {
            this.srcPort = value;
        }

        /**
         * Gets the value of the destPort property.
         * 
         */
        public long getDestPort() {
            return destPort;
        }

        /**
         * Sets the value of the destPort property.
         * 
         */
        public void setDestPort(long value) {
            this.destPort = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the accessTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessTime() {
            return accessTime;
        }

        /**
         * Sets the value of the accessTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessTime(String value) {
            this.accessTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="logAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="endFlag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="msgInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "logAmount",
        "endFlag",
        "msgInfo"
    })
    public static class Result {

        protected long logAmount;
        @XmlElement(required = true)
        protected BigInteger endFlag;
        protected String msgInfo;

        /**
         * Gets the value of the logAmount property.
         * 
         */
        public long getLogAmount() {
            return logAmount;
        }

        /**
         * Sets the value of the logAmount property.
         * 
         */
        public void setLogAmount(long value) {
            this.logAmount = value;
        }

        /**
         * Gets the value of the endFlag property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEndFlag() {
            return endFlag;
        }

        /**
         * Sets the value of the endFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEndFlag(BigInteger value) {
            this.endFlag = value;
        }

        /**
         * Gets the value of the msgInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMsgInfo() {
            return msgInfo;
        }

        /**
         * Sets the value of the msgInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMsgInfo(String value) {
            this.msgInfo = value;
        }

    }

}
