//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.common.utils.model.smmscmd;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commandInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="srcIp" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="destIp" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="srcPort" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="dstPort" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandId",
    "idcId",
    "commandInfo",
    "timeStamp"
})
@XmlRootElement(name = "logQuery")
public class LogQuery extends CommandBaseVo{
	private static final long serialVersionUID = -8023720915836412613L;
	protected long commandId;
    @XmlElement(required = true)
    protected String idcId;
    @XmlElement(required = true)
    protected CommandInfo commandInfo;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the commandId property.
     *
     */
    public long getCommandId() {
        return commandId;
    }

    /**
     * Sets the value of the commandId property.
     *
     */
    public void setCommandId(long value) {
        this.commandId = value;
    }

    /**
     * Gets the value of the idcId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdcId(String value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the commandInfo property.
     *
     * @return
     *     possible object is
     *     {@link CommandInfo }
     *
     */
    public CommandInfo getCommandInfo() {
        return commandInfo;
    }

    /**
     * Sets the value of the commandInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link CommandInfo }
     *
     */
    public void setCommandInfo(CommandInfo value) {
        this.commandInfo = value;
    }

    /**
     * Gets the value of the timeStamp property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="srcIp" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="destIp" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="srcPort" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="dstPort" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startTime",
        "endTime",
        "srcIp",
        "destIp",
        "srcPort",
        "dstPort",
        "protocolType",
        "url",
        "houseId"
    })
    public static class CommandInfo {

        @XmlElement(required = true)
        protected String startTime;
        protected String endTime;
        protected SrcIp srcIp;
        protected DestIp destIp;
        protected Long srcPort;
        protected Long dstPort;
        protected Long protocolType;
        protected String url;
        protected long houseId;

        /**
         * Gets the value of the startTime property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setStartTime(String value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the endTime property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setEndTime(String value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the srcIp property.
         *
         * @return
         *     possible object is
         *     {@link SrcIp }
         *
         */
        public SrcIp getSrcIp() {
            return srcIp;
        }

        /**
         * Sets the value of the srcIp property.
         *
         * @param value
         *     allowed object is
         *     {@link SrcIp }
         *
         */
        public void setSrcIp(SrcIp value) {
            this.srcIp = value;
        }

        /**
         * Gets the value of the destIp property.
         *
         * @return
         *     possible object is
         *     {@link DestIp }
         *
         */
        public DestIp getDestIp() {
            return destIp;
        }

        /**
         * Sets the value of the destIp property.
         *
         * @param value
         *     allowed object is
         *     {@link DestIp }
         *
         */
        public void setDestIp(DestIp value) {
            this.destIp = value;
        }

        /**
         * Gets the value of the srcPort property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSrcPort() {
            return srcPort;
        }

        /**
         * Sets the value of the srcPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSrcPort(Long value) {
            this.srcPort = value;
        }

        /**
         * Gets the value of the dstPort property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getDstPort() {
            return dstPort;
        }

        /**
         * Sets the value of the dstPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setDstPort(Long value) {
            this.dstPort = value;
        }

        /**
         * Gets the value of the protocolType property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getProtocolType() {
            return protocolType;
        }

        /**
         * Sets the value of the protocolType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setProtocolType(Long value) {
            this.protocolType = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the houseId property.
         * 
         */
        public long getHouseId() {
            return houseId;
        }

        /**
         * Sets the value of the houseId property.
         * 
         */
        public void setHouseId(long value) {
            this.houseId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startIp",
            "endIp"
        })
        public static class DestIp {

            @XmlElement(required = true)
            protected String startIp;
            @XmlElement(required = true)
            protected String endIp;

            /**
             * Gets the value of the startIp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartIp() {
                return startIp;
            }

            /**
             * Sets the value of the startIp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartIp(String value) {
                this.startIp = value;
            }

            /**
             * Gets the value of the endIp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndIp() {
                return endIp;
            }

            /**
             * Sets the value of the endIp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndIp(String value) {
                this.endIp = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="startIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="endIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startIp",
            "endIp"
        })
        public static class SrcIp {

            @XmlElement(required = true)
            protected String startIp;
            @XmlElement(required = true)
            protected String endIp;

            /**
             * Gets the value of the startIp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartIp() {
                return startIp;
            }

            /**
             * Sets the value of the startIp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartIp(String value) {
                this.startIp = value;
            }

            /**
             * Gets the value of the endIp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndIp() {
                return endIp;
            }

            /**
             * Sets the value of the endIp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndIp(String value) {
                this.endIp = value;
            }

        }

    }

}
